### ISSUE TITLE
Latest version of chalice breaking pip (Python 3.6)

### ISSUE THREAD

**Issue by rajkunkolienkar** [aws/chalice#806]
After installing chalice from pip, it seems to have installed the enum34 library, which breaks my pip. 

`Traceback (most recent call last):`
  `File "/usr/local/bin/pip3.6", line 4, in <module>`
  `  import re`
  `File "/usr/lib/python3.6/re.py", line 142, in <module>`
  `  class RegexFlag(enum.IntFlag):`
`AttributeError: module 'enum' has no attribute 'IntFlag'`

Fixed it by removing the enum34 distribution from site-packages.

**Comment by dstufft** [comment]
Are you able to provide steps to reproduce this? Generally Python ensures the stdlib comes first in ``sys.path`` and when I try to install both pip and enum34 into an environment locally, it all seems tow ork fine for me.

**Comment by rajkunkolienkar** [comment]
I am running the latest EC2 AMI. 

I created a virtualenv with Python 3.6, pip installed chalice. 
chalice downgraded pip from v10.0.1 to v.9.0.3 and installed successfully.
When I run pip after installing chalice, I get the error as stated above.

**Comment by dnorton** [comment]
Can we reopen this issue? I'm seeing the same problem.  It is because chalice is installing the module enum34.

```
Collecting argh>=0.24.1 (from watchdog==0.8.3->chalice->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/06/1c/e667a7126f0b84aaa1c56844337bf0ac12445d1beb9c8a6199a7314944bf/argh-0.26.2-py2.py3-none-any.whl
Installing collected packages: jmespath, six, python-dateutil, docutils, botocore, enum34, attrs, pathtools, PyYAML, argh, watchdog, typing, click, chalice, pbr, mock, PyMySQL, SQLAlchemy, s3transfer, boto3, dnspython, urllib3, certifi, idna, chardet, requests, aws-requests-auth
```

**Comment by dnorton** [comment]
Can we reopen this issue? I am experiencing the same problem with when installing chalice.

enum34 will not work with python 3.6 - https://stackoverflow.com/questions/45896474/installing-enum34-on-python-3-x-breaks-pip-for-python3-x

**Comment by DigiPutar** [comment]
I agree with @dnorton 
I am also facing the same issue while setting up the chalice environment over virtualenv on Amazon Linux machine AMI for Python 3.6

(venv3) [ec2-user@ip-xx.xxx.xxx.xxx ~]$ chalice --version
Traceback (most recent call last):
  File "/tmp/venv3/bin/chalice", line 4, in <module>
    import re
  File "/tmp/venv3/lib64/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

---- If I install it directly it works fine. Issue is to run the python3.6 and chalice on virtualenv.

**Comment by dnorton** [comment]
@dstufft, if you reopen this, I'll work on a fix for it.

**Comment by jamesls** [comment]
Taking a look, let me see if I can repro this.

@dnorton what would be the proposed fix?

**Comment by jamesls** [comment]
I tried following the repro steps, and here's what I got:

```
$ cat /etc/issue
Amazon Linux AMI release 2018.03
Kernel \r on an \m

$ sudo yum install python36
Loaded plugins: priorities, update-motd, upgrade-helper
Resolving Dependencies
--> Running transaction check
---> Package python36.x86_64 0:3.6.5-1.9.amzn1 will be installed
--> Processing Dependency: python36-libs(x86-64) = 3.6.5-1.9.amzn1 for package: python36-3.6.5-1.9.amzn1.x86_64
--> Processing Dependency: python36-setuptools for package: python36-3.6.5-1.9.amzn1.x86_64
--> Processing Dependency: python36-pip for package: python36-3.6.5-1.9.amzn1.x86_64
--> Processing Dependency: libpython3.6m.so.1.0()(64bit) for package: python36-3.6.5-1.9.amzn1.x86_64
--> Running transaction check
---> Package python36-libs.x86_64 0:3.6.5-1.9.amzn1 will be installed
---> Package python36-pip.noarch 0:9.0.3-1.26.amzn1 will be installed
---> Package python36-setuptools.noarch 0:36.2.7-1.33.amzn1 will be installed
--> Finished Dependency Resolution

$ mkdir /tmp/repro
$ virtualenv /tmp/repro/venv
New python executable in /tmp/repro/venv/bin/python2.7
Also creating executable in /tmp/repro/venv/bin/python
Installing setuptools, pip, wheel...done.
$ . venv/bin/activate
$ pip install chalice
Collecting chalice
  Downloading https://files.pythonhosted.org/packages/10/34/0b1ed27562fa836845d94cda96ec7f04b7f37242937a820e211018706968/chalice-1.5.0-py2.py3-none-any.whl (246kB)
    100% |████████████████████████████████| 256kB 14.2MB/s
Collecting attrs==17.4.0 (from chalice)
  Downloading https://files.pythonhosted.org/packages/b5/60/4e178c1e790fd60f1229a9b3cb2f8bc2f4cc6ff2c8838054c142c70b5adc/attrs-17.4.0-py2.py3-none-any.whl
Requirement already satisfied: pip<11,>=9 in ./venv/lib/python2.7/site-packages (from chalice) (10.0.1)
Collecting six<2.0.0,>=1.10.0 (from chalice)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting botocore<2.0.0,>=1.10.48 (from chalice)
  Downloading https://files.pythonhosted.org/packages/cb/6e/4d961f0c98007ba077a64626f4e0056e5351cca54653b15d12bb03c32110/botocore-1.10.58-py2.py3-none-any.whl (4.4MB)
    100% |████████████████████████████████| 4.4MB 7.9MB/s
Collecting click<7.0,>=6.6 (from chalice)
  Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 25.6MB/s
Collecting jmespath<1.0.0,>=0.9.3 (from chalice)
  Downloading https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
Collecting typing==3.6.4 (from chalice)
  Downloading https://files.pythonhosted.org/packages/0d/4d/4e5985d075d241d686a1663fa1f88b61d544658d08c1375c7c6aac32afc3/typing-3.6.4-py2-none-any.whl
Collecting enum34==1.1.6 (from chalice)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1; python_version >= "2.7" (from botocore<2.0.0,>=1.10.48->chalice)
  Downloading https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl (211kB)
    100% |████████████████████████████████| 215kB 30.2MB/s
Collecting docutils>=0.10 (from botocore<2.0.0,>=1.10.48->chalice)
  Downloading https://files.pythonhosted.org/packages/50/09/c53398e0005b11f7ffb27b7aa720c617aba53be4fb4f4f3f06b9b5c60f28/docutils-0.14-py2-none-any.whl (543kB)
    100% |████████████████████████████████| 552kB 29.4MB/s
Installing collected packages: attrs, six, python-dateutil, jmespath, docutils, botocore, click, typing, enum34, chalice
Successfully installed attrs-17.4.0 botocore-1.10.58 chalice-1.5.0 click-6.7 docutils-0.14 enum34-1.1.6 jmespath-0.9.3 python-dateutil-2.7.3 six-1.11.0 typing-3.6.4

$ pip list
Package         Version
--------------- -------
attrs           17.4.0
botocore        1.10.58
chalice         1.5.0
click           6.7
docutils        0.14
enum34          1.1.6
jmespath        0.9.3
pip             10.0.1
python-dateutil 2.7.3
setuptools      40.0.0
six             1.11.0
typing          3.6.4
wheel           0.31.1
```

Was there something else I can try that demonstrates the issue?  I'd like to understand what's going on.

**Comment by dnorton** [comment]
@jamesls, there is a python lib enum-compat that uses enum34 if the python is < 3.4 and the default enum if python >= 3.4 (that's from memory.)

**Comment by jamesls** [comment]
Reopening issue.  I've removed the label so hopefully that fixes things.
Cool, if it's just a package update to enum, that sounds good to me.

**Comment by dnorton** [comment]
@jamesls, I created PR https://github.com/aws/chalice/pull/905

Let me know if you need anything else to move this forward.

**Comment by stealthycoin** [comment]
This got merged in #905 closing.
